
    <div class="col-sm-8"><h3 style="text-align:center">Editar categoria</h3></div>
    <div class="container">
    <div class="col-sm-4 col-sm-offset-4">
        <form action="<?php echo APP_URL . "categorias/editar"; ?>" method="POST">
            <input type="hidden" name="id" value="<?php echo $this->categoria["id"]; ?>">
            <p>
                <label for="name">Nombre</label>
                <input type="text" name="name" value="<?php echo $this->categoria["name"]; ?>" class="form-control">
            </p>
            <p>
                <input type="submit" value="Guardar categoría" class="btn-primary">
            </p>
        </form>
    </div>
</div>
</div>