<h3 style="text-align:center">Lista de categorias</h3></div>
    </div>
    </br>
<div class="container">
        <div class="col-md-7 text-right">
        <a href="<?php echo APP_URL . "categorias/agregar"; ?>">
        <button class="btn btn-sm btn-success">Agregar categoria</button>
    </a>
</div>

<div class="col-md-12 mg-top-10">
        <table border="1" class="table table-bordered table-striped text-center">
        <tr style="text-align:center">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
        </tr>
        <?php foreach ($this->categorias as $categoria): ?>
            <tr>
                <td><?php echo $categoria["id"]; ?></td>
                <td><?php echo $categoria["name"]; ?></td>
                <td>
                    <a href="<?php echo APP_URL . "categorias/editar/" . $categoria["id"]; ?>">
                        <button class="btn btn-sm btn-primary">Editar</button>
                    </a> |
                    <a href="<?php echo APP_URL . "categorias/eliminar/" . $categoria["id"]; ?>">
                        <button class="btn btn-sm btn-danger">Eliminar</button>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>