<h3 style="text-align:center">Agregar cuenta</h3>
    <div class="container">
    <div class="col-sm-4 col-sm-offset-4">
        <form action="<?php echo APP_URL . "cuentas/agregar"; ?>" method="POST">
            <p>
                <label for="name">Nombre</label>
                <input type="text" name="name" class="form-control">
            </p>
            <p>
                <input class="btn btn-sm btn-success" type="submit" value="Guardar cuenta">
            </p>
        </form>
    </div>
</div>
</div>