 <h3 style="text-align:center">Editar cuenta</h2></div>
    <div class="container">
    <div class="col-sm-4 col-sm-offset-4">
        <form action="<?php echo APP_URL . "cuentas/editar"; ?>" method="POST">
            <input type="hidden" name="id" value="<?php echo $this->cuenta["id"]; ?>">
            <p>
                <label for="name">Nombre</label>
                <input type="text" name="name" value="<?php echo $this->cuenta["name"]; ?>" class="form-control">
            </p>
            <p>
                <input type="submit" value="Guardar cuenta" class="btn btn-sm btn-success">
            </p>
        </form>
    </div>
</div>
</div>